### ISSUE TITLE
Does the tool require an operating system?

### ISSUE THREAD

**Issue by MountainTang** [GrantZheng/kit#15]
I'm try `kit n s Hello` in Windows.But Kit throws an exception:
genModule: sh -c cd hello && go mod init hello => err:exec: "sh": executable file not found in %PATH% ,
time="2020-09-16T10:11:30+08:00" level=error msg="genModule: sh -c cd hello && go mod init hello => err:exec: \"sh\": executable file not found in %PATH% 

期待你的回复

**Comment by GrantZheng** [comment]
> I'm try `kit n s Hello` in Windows.But Kit throws an exception:
> genModule: sh -c cd hello && go mod init hello => err:exec: "sh": executable file not found in %PATH% ,
> time="2020-09-16T10:11:30+08:00" level=error msg="genModule: sh -c cd hello && go mod init hello => err:exec: "sh": executable file not found in %PATH%
> 
> 期待你的回复

这个在window上支持的不友好，最好在linux下面运行：）

**Comment by MountainTang** [comment]
windows运行目前时失败的，是否有后续的修改计划？

**Comment by speedoops** [comment]
> 这个在window上支持的不友好，最好在linux下面运行：）
如果只是sh依赖的话可以在Windows上用Git bash跑
