### ISSUE TITLE
ERRO[0000] exit status 1

### ISSUE THREAD

**Issue by kirinse** [GrantZheng/kit#17]
go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/XXX/Library/Caches/go-build"
GOENV="/Users/XXX/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/XXX/go/pkg/mod"
GONOPROXY="github.com/XXXX"
GONOSUMDB="github.com/XXXX"
GOOS="darwin"
GOPATH="/Users/XXX/go"
GOPRIVATE="github.com/XXXX"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xd/l04f3qld4rd_79_6w9dzhmf00000gn/T/go-build830253790=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

when ```kit g s -t grpc --dmw svc```, got ```ERRO[0000] exit status 1```,
after returned error, cmd dir missing, pkg/grpc/handler missing

but ```kit g s --dmw svc``` is ok.

**Comment by GrantZheng** [comment]
> go env
> 
> ```
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/Users/XXX/Library/Caches/go-build"
> GOENV="/Users/XXX/Library/Application Support/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOINSECURE=""
> GOMODCACHE="/Users/XXX/go/pkg/mod"
> GONOPROXY="github.com/XXXX"
> GONOSUMDB="github.com/XXXX"
> GOOS="darwin"
> GOPATH="/Users/XXX/go"
> GOPRIVATE="github.com/XXXX"
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> AR="ar"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xd/l04f3qld4rd_79_6w9dzhmf00000gn/T/go-build830253790=/tmp/go-build -gno-record-gcc-switches -fno-common"
> ```
> 
> when `kit g s -t grpc --dmw svc`, got `ERRO[0000] exit status 1`,
> after returned error, cmd dir missing, pkg/grpc/handler missing
> 
> but `kit g s --dmw svc` is ok.

Hi, do you use the latest code on the master? I cannot reproduce your problem
![image](https://user-images.githubusercontent.com/8568462/98777782-4e8daa00-242c-11eb-9bdb-ff20252aa6c4.png)

**Comment by kirinse** [comment]
@GrantZheng, 
thanks for your reply, yes, i'm using latest code on master branch.
```
go version go1.15.4
```

**Comment by GrantZheng** [comment]
> @GrantZheng,
> thanks for your reply, yes, i'm using latest code on master branch.
> 
> ```
> go version go1.15.4
> ```

Hi, I upgrade my go version to 1.15.4 and the generation code run correctly.  But when I run it on other system which do not install protoc-gen-go, I can reproduce your problem. Then I do as follows:
go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
cp protoc-gen-go /usr/local/bin 
It can solve that problem.
So, please make sure that your protoc-gen-go is installed correctly :)

**Comment by kirinse** [comment]
@GrantZheng, you are right, i did purge system space then protoc-gen-go missing.

working now. :) thanks.
