### ISSUE TITLE
ERRO[0000] exit status 1

### ISSUE THREAD

**Issue by jackywu** [GrantZheng/kit#18]
```
→ go version
go version go1.14.2 darwin/amd64

→  kit new service hello 
→  kit generate  service hello -t grpc
ERRO[0000] exit status 1

→ kit generate  service hello --debug  -t grpc
ERRO[0000] exit status 1
```

**Comment by GrantZheng** [comment]
> ```
> → go version
> go version go1.14.2 darwin/amd64
> 
> →  kit new service hello 
> →  kit generate  service hello -t grpc
> ERRO[0000] exit status 1
> 
> → kit generate  service hello --debug  -t grpc
> ERRO[0000] exit status 1
> ```
Hi, are you sure that your protoc-gen-go is installed correctly？https://github.com/GrantZheng/kit/issues/17

**Comment by jackywu** [comment]
@GrantZheng yes, installed, is there a way to display any verbose debug message?

**Comment by technolingo** [comment]
> @GrantZheng yes, installed, is there a way to display any verbose debug message?

Yes, I'm also facing the same issue. I see both `protoc-gen-go` and `protoc-gen-go-grpc` in my `$GOPATH/bin`, and `GOPATH` is also set correct in `zshrc`.

**Comment by GrantZheng** [comment]
> > @GrantZheng yes, installed, is there a way to display any verbose debug message?
> 
> Yes, I'm also facing the same issue. I see both `protoc-gen-go` and `protoc-gen-go-grpc` in my `$GOPATH/bin`, and `GOPATH` is also set correct in `zshrc`.

Hi, try to upgrade go version and use module feature ?

**Comment by diegoquiroz** [comment]
Hi, I'm facing the same **`ERRO[0000]`**.

Go version: `1.16.5`
OS: macOS 11.4


Steps to reproduce:
1. Installed protoc with Homebrew:
`brew install protobuf protoc-gen-go protoc-gen-go-grpc`
2. Kit generate: 
```
kit n s service_name
kit g s service_name --dmw
kit g s service_name -t grpc
```

**Comment by GrantZheng** [comment]
> Hi, I'm facing the same **`ERRO[0000]`**.
> 
> Go version: `1.16.5`
> OS: macOS 11.4
> 
> Steps to reproduce:
> 
> 1. Installed protoc with Homebrew:
>    `brew install protobuf protoc-gen-go protoc-gen-go-grpc`
> 2. Kit generate:
> 
> ```
> kit n s service_name
> kit g s service_name --dmw
> kit g s service_name -t grpc
> ``` 

Hi, try to use this method(https://grpc.io/docs/languages/go/quickstart/) to install ? I will add debug message for it and find a new environment to try to reproduce it.

**Comment by diegoquiroz** [comment]
Sorry for the late reply. Is still not working with any type of installation method (tried brew, go get and source)

**Comment by zeknox** [comment]
Hi All-

Also having this same issue when generating a service with type grpc.  Works great when removing the -t grpc flag.  Anyone have a workaround for this?

    % kit g s IP --dmw -t grpc --debug
    ERRO[0000] exit status 1

Versions

    Go version: go1.17 darwin/amd64
    OS: macOS 10.15.7

**Comment by 0x0ece** [comment]
Can anyone share a working config (go version, protoc --version; and maybe installation steps as docs got out of date)?

**Comment by oldmonad** [comment]
Hi has anyone been able to fix this?, can't seem to be able to get it to work, and I have tried all installation methods including this [one](https://github.com/GrantZheng/kit/issues/17#issuecomment-725404932)

**Comment by JianleiZhang** [comment]
add `option go_package` to the proto file.
![image](https://user-images.githubusercontent.com/7637056/143543759-1f0fde69-fe6e-45ba-913b-ede1bdbe5fa0.png)
rerun the kit command will be fine.
![image](https://user-images.githubusercontent.com/7637056/143543826-789eb06d-fc37-4470-9c57-cae4583238f8.png)

**Comment by Edwardz43** [comment]
> add `option go_package` to the proto file. ![image](https://user-images.githubusercontent.com/7637056/143543759-1f0fde69-fe6e-45ba-913b-ede1bdbe5fa0.png) rerun the kit command will be fine. ![image](https://user-images.githubusercontent.com/7637056/143543826-789eb06d-fc37-4470-9c57-cae4583238f8.png)

Can you please share you project structure ?  I faced the same issue and I'm not sure about that my project(folder) structure was correct or not.

**Comment by GrantZheng** [comment]
> Can anyone share a working config (go version, protoc --version; and maybe installation steps as docs got out of date)?

protoc --version
libprotoc 3.13.0

go version 
go version go1.15.4 darwin/amd64

**Comment by GrantZheng** [comment]
> > add `option go_package` to the proto file. ![image](https://user-images.githubusercontent.com/7637056/143543759-1f0fde69-fe6e-45ba-913b-ede1bdbe5fa0.png) rerun the kit command will be fine. ![image](https://user-images.githubusercontent.com/7637056/143543826-789eb06d-fc37-4470-9c57-cae4583238f8.png)
> 
> Can you please share you project structure ? I faced the same issue and I'm not sure about that my project(folder) structure was correct or not.

└── hello
    ├── cmd
    │   ├── main.go
    │   └── service
    │       ├── service.go
    │       └── service_gen.go
    ├── go.mod
    └── pkg
        ├── endpoint
        │   ├── endpoint.go
        │   └── endpoint_gen.go
        ├── grpc
        │   ├── handler.go
        │   ├── handler_gen.go
        │   └── pb
        │       ├── compile.sh
        │       ├── hello.pb.go
        │       └── hello.proto
        └── service
            ├── middleware.go
            └── service.go

**Comment by Edwardz43** [comment]
@JianleiZhang, @GrantZheng  thanks your help ! It works both  on MBP and WSL2 environment.

WSL2:
```
go version go1.17.2 linux/amd64
libprotoc 3.19.1
```
MBP:
```
go version go1.17.3 darwin/amd64
libprotoc 3.17.3
```

**Comment by Chanonry** [comment]
This was not a perfect fix for me.

Rerunning kit g s hello -t grpc failed to generate hello.pb.go. So I compiled and sorted out the folder structure which was fine, but it isn't clear to me why compilation failed for me?

Is the file structure above correct ?  I assume it should show compile.sh hello.pb.go & hello.proto within the pb folder not at the same level.

**Comment by rd7edlo** [comment]
> 
![截圖 2022-01-07 上午11 49 25](https://user-images.githubusercontent.com/74900703/148488552-48a90d2f-2ebc-4553-bfa3-45c5207c4c89.png)
try these steps and add `option go_package = "./SERVICE_NAME"` to .proto file

it works for me

**Comment by Edwardz43** [comment]
> This was not a perfect fix for me.
> 
> Rerunning kit g s hello -t grpc failed to generate hello.pb.go. So I compiled and sorted out the folder structure which was fine, but it isn't clear to me why compilation failed for me?
> 
> Is the file structure above correct ? I assume it should show compile.sh hello.pb.go & hello.proto within the pb folder not at the same level.

![截圖 2022-01-07 上午11 49 25](https://user-images.githubusercontent.com/25794152/148489121-f33a9bdb-f194-4a0d-8238-eaf05f415b68.png)

try these steps and add `option go_package = "./SERVICE_NAME"` to .proto file

it works for me

**Comment by Chanonry** [comment]
and that's my point. It does not work for me

**Comment by bootun** [comment]
@Chanonry now I contribute a pull request,  before it merges in the repository, you can use [bootun/kit](https://github.com/bootun/kit) to solve the problem

**Comment by bootun** [comment]
when generate gRPC code, `gokit cli` will now currently throw an exception
