### ISSUE TITLE
将文章移至项目内维护

### ISSUE THREAD

**Issue by bootun** [GrantZheng/kit#31]
should we consider of moving [this article](https://medium.com/@kujtimii.h/creating-a-todo-app-using-gokit-cli-20f066a58e1) to the project to maintenance? so we can change the content following the project changes. of course, we will mark the original author.

**Comment by lxxwilliam** [comment]
> should we consider of moving [this article](https://medium.com/@kujtimii.h/creating-a-todo-app-using-gokit-cli-20f066a58e1) to the project to maintenance? so we can change the content following the project changes. of course, we will mark the original author.

hi,i meet some problems like this:
PS D:\projects\go-kit\mydemo> kit g s hello -t  grpc
time="2022-02-07T17:04:43+08:00" level=warning msg="==============================================================="
time="2022-02-07T17:04:43+08:00" level=warning msg="The GRPC implementation is not finished you need to update your"
time="2022-02-07T17:04:43+08:00" level=warning msg=" service proto buffer and run the compile script."
time="2022-02-07T17:04:43+08:00" level=warning msg=---------------------------------------------------------------
time="2022-02-07T17:04:43+08:00" level=warning msg="You also need to implement the Encoders and Decoders!"
time="2022-02-07T17:04:43+08:00" level=warning msg="==============================================================="
 so,about the part of the grpc in this article,could you please add some steps like http,  thanks.

**Comment by bootun** [comment]
> so,about the part of the grpc in this article,could you please add some steps like http, thanks.   

great idea! I will collect suggestions and add them to the article but maybe not soon.

**Comment by lxxwilliam** [comment]
> > so,about the part of the grpc in this article,could you please add some steps like http, thanks.
> 
> great idea! I will collect suggestions and add them to the article but maybe not soon.

great! I am waiting for u.
