### ISSUE TITLE
ERRO[0000] exit status 2 

### ISSUE THREAD

**Issue by jack17529** [GrantZheng/kit#4]
When I use the command to make a new service with name as first letter capital.
`kit new service XYZ`    
I get the error  
```
exit status 2
ERRO[0000] exit status 2
```  

Please help

**Comment by GrantZheng** [comment]
> When I use the command to make a new service
> `kit new service XYZ`
> I get the error
> `exit status 2 ERRO[0000] exit status 2`
> 
> Please help

Hi, I can not reproduce your problem, could you show me your go env ?

I run it on my mac and the go env is below: 

> GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/zy/Library/Caches/go-build"
GOENV="/Users/zy/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zy/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_9/nstx65510m98m898c7qxn8600000gn/T/go-build241633003=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by jack17529** [comment]
It only happens when the first letter of the service name is capital, otherwise it does not.  
Here is output of my go env  
GO111MODULE=""  
GOARCH="amd64"  
GOBIN=""  
GOCACHE="/home/faith/.cache/go-build"  
GOENV="/home/faith/.config/go/env"  
GOEXE=""  
GOFLAGS=""  
GOHOSTARCH="amd64"  
GOHOSTOS="linux"  
GONOPROXY=""  
GONOSUMDB=""  
GOOS="linux"  
GOPATH="/home/faith/Go"  
GOPRIVATE=""  
GOPROXY="https://proxy.golang.org,direct"  
GOROOT="/usr/local/go"  
GOSUMDB="sum.golang.org"  
GOTMPDIR=""  
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"  
GCCGO="gccgo"  
AR="ar"  
CC="gcc"  
CXX="g++"  
CGO_ENABLED="1"  
GOMOD=""  
CGO_CFLAGS="-g -O2"  
CGO_CPPFLAGS=""  
CGO_CXXFLAGS="-g -O2"  
CGO_FFLAGS="-g -O2"  
CGO_LDFLAGS="-g -O2"  
PKG_CONFIG="pkg-config"  
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build189892159=/tmp/go-build -gno-record-gcc-switches"

**Comment by GrantZheng** [comment]
> It only happens when the first letter of the service name is capital, otherwise it does not.
> Here is output of my go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/faith/.cache/go-build"
> GOENV="/home/faith/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/faith/Go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build189892159=/tmp/go-build -gno-record-gcc-switches"

Oh, I can reproduce it，I will fix it as soon as possible, thanks! :)

**Comment by GrantZheng** [comment]
@jack17529 Hi，I'm sorry to solve it so long，I test it and update it on the master branch, please update, thanks :)
