### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by Bingjian-Zhu** [GrantZheng/kit#6]
建议把修改BUG的代码合并到源代码中，维护共同维护一份代码会省事点

**Comment by GrantZheng** [comment]
@Bingjian-Zhu 好的，是指合并到https://github.com/kujtimiihoxha/kit 这里吗？我也挺想合的，但是作者好像不怎么活跃，我再去联系下他

**Comment by Bingjian-Zhu** [comment]
@GrantZheng 好，感谢
