### ISSUE TITLE
leftover github.com/kujtimiihoxha link

### ISSUE THREAD

**Issue by fahimbagar** [GrantZheng/kit#8]
Hi @GrantZheng , I check your repo and it seems maintained rather than the original kit. Do you have plan to continue it? if yes, I'll try to make contribution here.

This is the example:
```
$ grep -ira "kujtimiihoxha"
go.mod:module github.com/kujtimiihoxha/kit
```

I think above example is one of reason why `go get github.com/GrantZheng/kit` not working. I can create PR if this repo will be maintained. I also heavily use kit, so it will better for community too. 

I've also check that the LICENSE is MIT, so you free to modify and distribute it by yourself.

**Comment by GrantZheng** [comment]
@fahimbagar Hi, I plan to continue to maintain it, and I very glad to do it with you. You could create PR for it. :)

**Comment by fahimbagar** [comment]
Great then. I hope this repo will continue further.

**Comment by GrantZheng** [comment]
> Great then. I hope this repo will continue further.

Let's work together :)
